// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { RootItemsGetData, RootItemsGetError, RootItemsGetResponse, LikeItemsLikePutData, LikeItemsLikePutError, LikeItemsLikePutResponse, DislikeItemsDislikePutData, DislikeItemsDislikePutError, DislikeItemsDislikePutResponse, RootGetError, RootGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Root
 */
export const rootItemsGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RootItemsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootItemsGetResponse, RootItemsGetError, ThrowOnError>({
        ...options,
        url: '/items/'
    });
};

/**
 * Like
 */
export const likeItemsLikePut = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LikeItemsLikePutData, ThrowOnError>) => {
    return (options?.client ?? client).put<LikeItemsLikePutResponse, LikeItemsLikePutError, ThrowOnError>({
        ...options,
        url: '/items/like/'
    });
};

/**
 * Dislike
 */
export const dislikeItemsDislikePut = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DislikeItemsDislikePutData, ThrowOnError>) => {
    return (options?.client ?? client).put<DislikeItemsDislikePutResponse, DislikeItemsDislikePutError, ThrowOnError>({
        ...options,
        url: '/items/dislike/'
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponse, RootGetError, ThrowOnError>({
        ...options,
        url: '/'
    });
};