// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser, urlSearchParamsBodySerializer } from '@hey-api/client-fetch';
import type { LoginTokenPostData, LoginTokenPostError, LoginTokenPostResponse, RootItemsGetData, RootItemsGetError, RootItemsGetResponse, LikeItemsLikePutData, LikeItemsLikePutError, LikeItemsLikePutResponse, RootGetError, RootGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Login
 */
export const loginTokenPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LoginTokenPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LoginTokenPostResponse, LoginTokenPostError, ThrowOnError>({
        ...options,
        ...urlSearchParamsBodySerializer,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        },
        url: '/token'
    });
};

/**
 * Root
 */
export const rootItemsGet = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RootItemsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootItemsGetResponse, RootItemsGetError, ThrowOnError>({
        ...options,
        url: '/items/'
    });
};

/**
 * Like
 */
export const likeItemsLikePut = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LikeItemsLikePutData, ThrowOnError>) => {
    return (options?.client ?? client).put<LikeItemsLikePutResponse, LikeItemsLikePutError, ThrowOnError>({
        ...options,
        url: '/items/like/'
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponse, RootGetError, ThrowOnError>({
        ...options,
        url: '/'
    });
};