// This file is auto-generated by @hey-api/openapi-ts

export type Feed = {
    id: number;
    title: string;
    link: string;
    language: (Language | null);
    tags: Array<Tag>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    id: number;
    title: string;
    link: string;
    published: string;
    summary: (string | null);
    feed: Feed;
    like: (LikeStatus | null);
    magic: (number | null);
};

export type Language = 'English' | 'German' | 'Swedish';

export type LikeStatus = 1 | 0 | -1;

export type Tag = {
    id: number;
    name: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type RootItemsGetData = {
    query: {
        dt_from: string;
        dt_to: string;
    };
};

export type RootItemsGetResponse = (Array<Item>);

export type RootItemsGetError = (HTTPValidationError);

export type LikeItemsLikePutData = {
    query: {
        item_id: number;
    };
};

export type LikeItemsLikePutResponse = (unknown);

export type LikeItemsLikePutError = (HTTPValidationError);

export type DislikeItemsDislikePutData = {
    query: {
        item_id: number;
    };
};

export type DislikeItemsDislikePutResponse = (unknown);

export type DislikeItemsDislikePutError = (HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;