// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Feed = {
    id: number;
    title: string;
    link: string;
    language: (Language | null);
    tags: Array<Tag>;
    displayed: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    id: number;
    title: string;
    link: string;
    published: string;
    summary: (string | null);
    feed: Feed;
    like: (LikeStatus | null);
    magic: (number | null);
};

export type Language = 'English' | 'German' | 'Swedish';

export type LikeStatus = 1 | 0 | -1;

export type Tag = {
    id: number;
    name: string;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginTokenPostData = {
    body: Body_login_token_post;
};

export type LoginTokenPostResponse = (Token);

export type LoginTokenPostError = (HTTPValidationError);

export type TagsFeedsTagsGetResponse = (Array<Tag>);

export type TagsFeedsTagsGetError = unknown;

export type LanguagesFeedsLanguagesGetResponse = (Array<Language>);

export type LanguagesFeedsLanguagesGetError = unknown;

export type FeedFeedsFeedFeedIdGetData = {
    path: {
        feed_id: number;
    };
};

export type FeedFeedsFeedFeedIdGetResponse = (Feed);

export type FeedFeedsFeedFeedIdGetError = (HTTPValidationError);

export type AttachTagFeedsFeedFeedIdAttachTagPutData = {
    path: {
        feed_id: number;
    };
    query: {
        tag_id: number;
    };
};

export type AttachTagFeedsFeedFeedIdAttachTagPutResponse = (unknown);

export type AttachTagFeedsFeedFeedIdAttachTagPutError = (HTTPValidationError);

export type DetachTagFeedsFeedFeedIdDetachTagDeleteData = {
    path: {
        feed_id: number;
    };
    query: {
        tag_id: number;
    };
};

export type DetachTagFeedsFeedFeedIdDetachTagDeleteResponse = (unknown);

export type DetachTagFeedsFeedFeedIdDetachTagDeleteError = (HTTPValidationError);

export type CreateAndAttachTagFeedsFeedFeedIdCreateAndAttachTagPutData = {
    path: {
        feed_id: number;
    };
    query: {
        tag_name: string;
    };
};

export type CreateAndAttachTagFeedsFeedFeedIdCreateAndAttachTagPutResponse = (Tag);

export type CreateAndAttachTagFeedsFeedFeedIdCreateAndAttachTagPutError = (HTTPValidationError);

export type AttachUserFeedsFeedFeedIdAttachUserPutData = {
    path: {
        feed_id: number;
    };
};

export type AttachUserFeedsFeedFeedIdAttachUserPutResponse = (unknown);

export type AttachUserFeedsFeedFeedIdAttachUserPutError = (HTTPValidationError);

export type DetachUserFeedsFeedFeedIdDetachUserDeleteData = {
    path: {
        feed_id: number;
    };
};

export type DetachUserFeedsFeedFeedIdDetachUserDeleteResponse = (unknown);

export type DetachUserFeedsFeedFeedIdDetachUserDeleteError = (HTTPValidationError);

export type UpdateFeedFeedsFeedFeedIdUpdateFeedPostData = {
    path: {
        feed_id: number;
    };
    query: {
        language?: (Language | null);
        link: string;
        title: string;
    };
};

export type UpdateFeedFeedsFeedFeedIdUpdateFeedPostResponse = (unknown);

export type UpdateFeedFeedsFeedFeedIdUpdateFeedPostError = (HTTPValidationError);

export type RootItemsGetData = {
    query: {
        dt_from: string;
        dt_to: string;
        languages?: (Array<Language> | null);
        tags?: (Array<(number)> | null);
    };
};

export type RootItemsGetResponse = (Array<Item>);

export type RootItemsGetError = (HTTPValidationError);

export type LikeItemsLikePutData = {
    query: {
        item_id: number;
        score: LikeStatus;
    };
};

export type LikeItemsLikePutResponse = (unknown);

export type LikeItemsLikePutError = (HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;